-- MySQL Script generated by MySQL Workbench
-- Tue Jan  1 16:12:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_group` (
  `user_group_id` INT NOT NULL AUTO_INCREMENT,
  `user_group_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`user_group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_link_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_link_groups` (
  `user_link_groups` INT NOT NULL AUTO_INCREMENT,
  `user_group_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_link_groups`),
  INDEX `fk_user_link_groups_user_group_idx` (`user_group_id` ASC) VISIBLE,
  INDEX `fk_user_link_groups_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_link_groups_user_group`
    FOREIGN KEY (`user_group_id`)
    REFERENCES `mydb`.`user_group` (`user_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_link_groups_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
